@echo off
del Conway.prg

if not exist tmp mkdir tmp
echo ;This file is automatically generated by BuildIt.bat >tmp\FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>tmp\FingerPrint.a

..\acme.exe --lib ..\ -v4 --msvc Conway.a
if not exist Conway.prg goto error
..\bin\LZMPi.exe -c64mbu Conway.prg Conway.prg $800 >t.txt
if not exist Conway.prg goto error
goto end
:error
echo Conway.prg not created!
exit /B -1
:end
